"use client";

import { useMemo, useState } from "react";
import type { BusinessAttachment, EventParticipant, EventRecord, EventUpdate, MonitoringAlert, MonitoringAsset, Organization, ResourceAsset, ResourceDispatch, RiskRecord, TaskFeedback, TaskRecord, Warehouse } from "@/lib/types";
import { StatusBadge } from "./product-pages";

type Marker = { id: string; name: string; category: string; longitude: number; latitude: number; urgent?: boolean };

const dispatchText: Record<ResourceDispatch["status"], string> = { requested: "待审批", approved: "已批准", rejected: "已拒绝", dispatched: "已出动", arrived: "已到场", returned: "已归队" };

function SituationMap({ event, events, risks, resources, warehouses, assets, alerts }: { event?: EventRecord; events: EventRecord[]; risks: RiskRecord[]; resources: ResourceAsset[]; warehouses: Warehouse[]; assets: MonitoringAsset[]; alerts: MonitoringAlert[] }) {
  const markers = useMemo(() => {
    const result: Marker[] = [];
    for (const item of events) if (item.longitude && item.latitude) result.push({ id: `event-${item.id}`, name: `${item.event_type}·${item.area}`, category: "事件", longitude: item.longitude, latitude: item.latitude, urgent: item.status !== "已结案" });
    for (const item of risks) if (item.longitude && item.latitude) result.push({ id: `risk-${item.id}`, name: item.name, category: "风险点", longitude: item.longitude, latitude: item.latitude, urgent: item.status !== "已回写" });
    for (const item of resources) if (item.longitude && item.latitude) result.push({ id: `resource-${item.id}`, name: item.name, category: item.asset_type === "facility" ? "避灾场所" : item.asset_type === "vehicle" ? "车辆" : "救援力量", longitude: item.longitude, latitude: item.latitude, urgent: item.status === "dispatched" });
    for (const item of warehouses) if (item.longitude && item.latitude) result.push({ id: `warehouse-${item.id}`, name: item.name, category: "仓库", longitude: item.longitude, latitude: item.latitude });
    for (const item of assets) result.push({ id: `asset-${item.id}`, name: item.name, category: "监测设备", longitude: item.longitude, latitude: item.latitude, urgent: alerts.some((alert) => alert.asset_id === item.id && !["closed", "converted"].includes(alert.status)) });
    return result;
  }, [events, risks, resources, warehouses, assets, alerts]);
  if (!markers.length) return <p className="empty">暂无带坐标的事件、风险或资源。</p>;
  const xs = markers.map((item) => item.longitude); const ys = markers.map((item) => item.latitude);
  const minX = Math.min(...xs) - .01; const maxX = Math.max(...xs) + .01; const minY = Math.min(...ys) - .01; const maxY = Math.max(...ys) + .01;
  return <div className="situation-map" role="img" aria-label="事件、风险、救援力量、车辆、仓库、避灾场所和告警设备态势图">
    <div className="map-grid" />
    {markers.map((marker) => <div key={marker.id} className={`situation-marker ${marker.urgent ? "urgent" : ""} ${marker.id === `event-${event?.id}` ? "focus" : ""}`} style={{ left: `${5 + (marker.longitude - minX) / (maxX - minX || 1) * 90}%`, top: `${90 - (marker.latitude - minY) / (maxY - minY || 1) * 80}%` }} title={`${marker.category}｜${marker.name}`}><i /> <span>{marker.name}</span><small>{marker.category}</small></div>)}
    <div className="map-legend">{["事件", "风险点", "救援力量", "车辆", "仓库", "避灾场所", "监测设备"].map((item) => <span key={item}>{item}</span>)}</div>
  </div>;
}

export function AdvancedCommandCenter({ selectedEvent, events, tasks, risks, resources, warehouses, assets, alerts, participants, updates, attachments, feedbacks, dispatches, organizations, writable, admin, onSelectEvent, onAddParticipant, onAddUpdate, onDecideUpdate, onUpload, onDownload, onAddFeedback, onReviewFeedback }: {
  selectedEvent?: EventRecord; events: EventRecord[]; tasks: TaskRecord[]; risks: RiskRecord[]; resources: ResourceAsset[]; warehouses: Warehouse[]; assets: MonitoringAsset[]; alerts: MonitoringAlert[];
  participants: EventParticipant[]; updates: EventUpdate[]; attachments: BusinessAttachment[]; feedbacks: TaskFeedback[]; dispatches: ResourceDispatch[]; organizations: Organization[];
  writable: boolean; admin: boolean; onSelectEvent: (id: string) => void; onAddParticipant: (eventId: string, form: FormData) => void; onAddUpdate: (event: EventRecord, form: FormData) => void; onDecideUpdate: (event: EventRecord, update: EventUpdate, approve: boolean) => void; onUpload: (type: BusinessAttachment["entity_type"], id: string, file?: File, category?: string) => void; onDownload: (attachment: BusinessAttachment) => void; onAddFeedback: (task: TaskRecord, form: FormData) => void; onReviewFeedback: (task: TaskRecord, approve: boolean, reason?: string) => void;
}) {
  const [seat, setSeat] = useState<"duty" | "leader" | "department">("duty");
  const [bigScreen, setBigScreen] = useState(false);
  const scopedTasks = selectedEvent ? tasks.filter((item) => item.event_id === selectedEvent.id) : [];
  const scopedUpdates = selectedEvent ? updates.filter((item) => item.event_id === selectedEvent.id) : [];
  const scopedParticipants = selectedEvent ? participants.filter((item) => item.event_id === selectedEvent.id) : [];
  const pendingApprovals = scopedUpdates.filter((item) => item.update_type === "审批申请" && item.approval_status === "pending");
  const timeline = selectedEvent ? [
    { id: `event-${selectedEvent.id}`, time: selectedEvent.happened_at, title: "事件发生", content: selectedEvent.description, type: "事件" },
    ...scopedUpdates.map((item) => ({ id: `update-${item.id}`, time: item.created_at, title: item.title, content: item.content, type: item.update_type })),
    ...scopedTasks.map((item) => ({ id: `task-${item.id}`, time: item.feedback_at || item.completed_at || item.created_at, title: `${item.title} · ${item.status}`, content: item.feedback || item.assignee, type: "指令" })),
    ...dispatches.filter((item) => item.event_id === selectedEvent.id).map((item) => ({ id: `dispatch-${item.id}`, time: item.updated_at, title: `资源${dispatchText[item.status]}`, content: resources.find((resource) => resource.id === item.resource_id)?.name || "应急资源", type: "资源" })),
  ].sort((a, b) => +new Date(b.time) - +new Date(a.time)) : [];
  return <section className={`command-deep ${bigScreen ? "command-big-screen" : ""}`}>
    <div className="command-viewbar"><div className="seat-tabs" role="tablist" aria-label="指挥席位视图"><button className={seat === "duty" ? "active" : ""} onClick={() => setSeat("duty")}>值班席</button><button className={seat === "leader" ? "active" : ""} onClick={() => setSeat("leader")}>领导席</button><button className={seat === "department" ? "active" : ""} onClick={() => setSeat("department")}>部门席</button></div><div className="actions"><StatusBadge mode={alerts.some((item) => !["closed", "converted"].includes(item.status)) ? "external" : "real"}>{alerts.filter((item) => !["closed", "converted"].includes(item.status)).length} 条活动告警</StatusBadge><button onClick={() => setBigScreen((value) => !value)}>{bigScreen ? "退出大屏" : "进入大屏"}</button></div></div>
    <div className="multi-incident-strip">{events.filter((item) => !["已结案", "已终止"].includes(item.status)).map((item) => <button key={item.id} className={item.id === selectedEvent?.id ? "active" : ""} onClick={() => onSelectEvent(item.id)}><b>{item.event_type}</b><span>{item.response_level} · {item.area}</span><small>{item.status}</small></button>)}</div>
    <div className="command-board-grid"><section className="panel map-panel"><div className="split"><div><h2>事件态势一张图</h2><small>事件、风险、力量、仓库、场所与设备统一落图</small></div><StatusBadge>{seat === "duty" ? "全过程操作" : seat === "leader" ? "决策摘要" : "本部门协同"}</StatusBadge></div><SituationMap event={selectedEvent} events={events} risks={risks} resources={resources} warehouses={warehouses} assets={assets} alerts={alerts} /></section>
      <section className="panel live-timeline"><div className="split"><h2>实时动态</h2><small>数据库变更自动刷新</small></div><div className="timeline">{timeline.slice(0, seat === "leader" ? 8 : 16).map((item) => <article key={item.id}><StatusBadge>{item.type}</StatusBadge><b>{item.title}</b><p>{item.content}</p><small>{new Date(item.time).toLocaleString("zh-CN")}</small></article>)}</div></section></div>
    {selectedEvent && seat !== "leader" && <div className="command-operations-grid"><details className="panel" open><summary><b>事件续报与状态申请</b><small>升级、降级、终止和结案必须审批</small></summary><form className="form compact-form" action={(form) => onAddUpdate(selectedEvent, form)}><label>动作<select name="action"><option>续报</option><option>处置记录</option><option>升级</option><option>降级</option><option>终止</option><option>结案</option></select></label><label>标题<input name="title" placeholder="第二次续报" /></label><label>目标响应等级<select name="targetLevel" defaultValue={selectedEvent.response_level}><option>I级</option><option>II级</option><option>III级</option><option>IV级</option></select></label><label>内容<textarea name="content" rows={3} required /></label><div className="weight-grid"><label>经度<input name="longitude" type="number" step="0.000001" /></label><label>纬度<input name="latitude" type="number" step="0.000001" /></label></div><button className="primary" disabled={!writable}>提交并进入时间线</button></form>{pendingApprovals.map((item) => <article className="approval-item" key={item.id}><b>{item.title}</b><p>{item.content}</p><small>{item.from_level}{item.to_level ? ` → ${item.to_level}` : ""}</small><div className="actions"><button className="primary" disabled={!admin} onClick={() => onDecideUpdate(selectedEvent, item, true)}>审批通过</button><button disabled={!admin} onClick={() => onDecideUpdate(selectedEvent, item, false)}>退回申请</button></div></article>)}</details>
      <details className="panel"><summary><b>参与单位与联络</b><small>{scopedParticipants.length} 个协同单位</small></summary><form className="form compact-form" action={(form) => onAddParticipant(selectedEvent.id, form)}><label>从组织树选择<select name="organizationId"><option value="">手工填写</option>{organizations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>单位名称<input name="organizationName" required /></label><label>事件职责<input name="responsibility" required /></label><label>联系人<input name="contactName" /></label><label>联系电话<input name="contactPhone" /></label><button className="primary" disabled={!writable}>加入协同</button></form>{scopedParticipants.map((item) => <article className="recommend" key={item.id}><div><b>{item.organization_name}</b><p>{item.responsibility}</p><small>{item.contact_name} {item.contact_phone}</small></div></article>)}</details>
      <details className="panel"><summary><b>现场图片与附件</b><small>{attachments.filter((item) => item.entity_type === "event" && item.entity_id === selectedEvent.id).length} 个文件</small></summary><label className="file-drop">上传事件图片或文件<input type="file" accept="image/*,.pdf,.docx,.xlsx,.txt" onChange={(event) => onUpload("event", selectedEvent.id, event.target.files?.[0], event.target.files?.[0]?.type.startsWith("image/") ? "现场图片" : "文件")} /></label><div className="attachment-list">{attachments.filter((item) => item.entity_type === "event" && item.entity_id === selectedEvent.id).map((item) => <button key={item.id} onClick={() => onDownload(item)}><b>{item.category}</b><span>{item.file_name}</span><small>{Math.max(1, Math.round(item.file_size / 1024))} KB</small></button>)}</div></details></div>}
    {selectedEvent && seat === "duty" && <section className="panel"><h2>现场反馈复核台</h2><div className="feedback-grid">{scopedTasks.map((task) => <article key={task.id}><div className="split"><b>{task.title}</b><StatusBadge mode={task.review_status === "returned" ? "external" : task.review_status === "approved" ? "real" : "simulated"}>{task.review_status === "returned" ? "已退回" : task.review_status === "approved" ? "已通过" : "待反馈/待复核"}</StatusBadge></div><p>{task.assignee} · {task.status}</p>{feedbacks.filter((item) => item.task_id === task.id).slice(0, 3).map((item) => <blockquote key={item.id}>{item.content}<small>{item.feedback_type} · {new Date(item.created_at).toLocaleString("zh-CN")}</small></blockquote>)}{task.status !== "已完成" && <form className="form compact-form" action={(form) => onAddFeedback(task, form)}><label>现场文字反馈<textarea name="content" rows={2} required /></label><div className="weight-grid"><label>经度<input name="longitude" type="number" step="0.000001" /></label><label>纬度<input name="latitude" type="number" step="0.000001" /></label></div><label>现场图片/文件<input type="file" accept="image/*,.pdf,.docx,.xlsx" onChange={(event) => onUpload("task", task.id, event.target.files?.[0], "现场反馈附件")} /></label><button disabled={!writable}>提交反馈</button></form>}{task.status === "已反馈" && <div className="actions"><button className="primary" disabled={!writable} onClick={() => onReviewFeedback(task, true)}>复核通过</button><button disabled={!writable} onClick={() => onReviewFeedback(task, false, window.prompt("填写退回原因") || "")}>退回补充</button></div>}</article>)}</div></section>}
  </section>;
}
