"use client";

import { useMemo, useState } from "react";
import { latestReadingByAsset, monitoringMetrics } from "@/lib/monitoring-engine";
import type { MonitoringAlert, MonitoringAlertAction, MonitoringAsset, MonitoringDomain, MonitoringReading, MonitoringRule } from "@/lib/types";
import { StatusBadge } from "./product-pages";
import { TyphoonRainMap } from "./typhoon-rain-map";

const assetLabels: Record<string, string> = { rain_station: "雨情测站", water_station: "水情测站", depth_sensor: "积水监测", wind_station: "风情测站", gas_sensor: "气体探测", bridge_sensor: "桥梁监测", fire_sensor: "消防水压", video: "视频监控" };
const alertLabels = { open: "待认领", claimed: "已认领", verified: "已复核", converted: "已转事件", closed: "已关闭" } as const;

function TrendChart({ readings }: { readings: MonitoringReading[] }) {
  if (!readings.length) return <p className="empty">暂无历史监测值。</p>;
  const sorted = [...readings].sort((a, b) => +new Date(a.measured_at) - +new Date(b.measured_at)).slice(-12);
  const values = sorted.map((item) => item.value); const min = Math.min(...values); const max = Math.max(...values); const span = max - min || 1;
  const points = sorted.map((item, index) => `${24 + index * (552 / Math.max(sorted.length - 1, 1))},${148 - ((item.value - min) / span) * 112}`).join(" ");
  return <div className="trend-chart"><svg viewBox="0 0 600 180" role="img" aria-label="最近监测值趋势"><line x1="24" y1="148" x2="576" y2="148" /><polyline points={points} />{sorted.map((item, index) => <circle key={item.id} cx={24 + index * (552 / Math.max(sorted.length - 1, 1))} cy={148 - ((item.value - min) / span) * 112} r="4"><title>{`${item.value}${item.unit} · ${new Date(item.measured_at).toLocaleString("zh-CN")}`}</title></circle>)}</svg><div className="split"><small>{min} {sorted[0].unit}</small><b>最新 {sorted.at(-1)?.value} {sorted.at(-1)?.unit}</b><small>{max} {sorted[0].unit}</small></div></div>;
}

function AssetMap({ assets, alerts, selectedId, onSelect }: { assets: MonitoringAsset[]; alerts: MonitoringAlert[]; selectedId: string; onSelect: (id: string) => void }) {
  if (!assets.length) return <p className="empty">暂无带坐标的设备。</p>;
  const longs = assets.map((item) => item.longitude); const lats = assets.map((item) => item.latitude); const minX = Math.min(...longs) - .01; const maxX = Math.max(...longs) + .01; const minY = Math.min(...lats) - .01; const maxY = Math.max(...lats) + .01;
  return <div className="asset-map" aria-label="监测设备位置示意图"><div className="map-grid" />{assets.map((asset) => { const left = ((asset.longitude - minX) / (maxX - minX || 1)) * 90 + 5; const top = (1 - (asset.latitude - minY) / (maxY - minY || 1)) * 80 + 10; const active = alerts.some((alert) => alert.asset_id === asset.id && alert.status !== "closed"); return <button key={asset.id} className={`map-marker ${active ? "danger" : ""} ${asset.id === selectedId ? "selected" : ""}`} style={{ left: `${left}%`, top: `${top}%` }} onClick={() => onSelect(asset.id)} title={`${asset.name} · ${asset.area}`}><span>{active ? "!" : "●"}</span><small>{asset.name}</small></button>; })}</div>;
}

export function MonitoringCenterPage({ domain, assets, readings, rules, alerts, actions, writable, onAddAsset, onAddRule, onIngest, onAlertAction }: { domain: MonitoringDomain; assets: MonitoringAsset[]; readings: MonitoringReading[]; rules: MonitoringRule[]; alerts: MonitoringAlert[]; actions: MonitoringAlertAction[]; writable: boolean; onAddAsset: (domain: MonitoringDomain, form: FormData) => void; onAddRule: (domain: MonitoringDomain, form: FormData) => void; onIngest: (asset: MonitoringAsset, form: FormData) => void; onAlertAction: (alert: MonitoringAlert, action: "claim" | "verify" | "convert" | "close") => void }) {
  const scopedAssets = assets.filter((item) => item.domain === domain); const assetIds = new Set(scopedAssets.map((item) => item.id));
  const scopedReadings = readings.filter((item) => assetIds.has(item.asset_id)); const scopedRules = rules.filter((item) => item.domain === domain); const scopedAlerts = alerts.filter((item) => assetIds.has(item.asset_id));
  const [selectedId, setSelectedId] = useState(scopedAssets[0]?.id || ""); const selected = scopedAssets.find((item) => item.id === selectedId) || scopedAssets[0];
  const latest = useMemo(() => latestReadingByAsset(scopedReadings), [scopedReadings]); const metrics = monitoringMetrics(scopedAssets, scopedReadings, scopedAlerts);
  const title = domain === "typhoon" ? "台汛卫士" : "城市安全综合监管";
  const typeOptions = domain === "typhoon" ? [["rain_station", "雨情测站"], ["water_station", "水情测站"], ["depth_sensor", "积水监测"], ["wind_station", "风情测站"]] : [["gas_sensor", "气体探测"], ["bridge_sensor", "桥梁监测"], ["fire_sensor", "消防水压"], ["video", "视频监控"]];
  return <><div className="pagehead"><div><span className="eyebrow">UNIFIED MONITORING COMMAND CENTER</span><h1>{title}</h1><p>统一设备、测站、监测值、阈值规则和告警处置；真实接口可通过适配器替换。</p></div><StatusBadge mode="simulated">当前外部实时数据为模拟</StatusBadge></div>
    <div className="metrics"><div className="metric"><span>设备在线率</span><strong>{metrics.onlineRate}%</strong><small>{scopedAssets.filter((item) => item.status === "online").length}/{scopedAssets.length} 在线</small></div><div className="metric"><span>未关闭告警</span><strong>{metrics.activeAlerts}</strong><small>严重 {metrics.criticalAlerts} 条</small></div><div className="metric"><span>监测值</span><strong>{metrics.readingCount}</strong><small>历史序列可追溯</small></div><div className="metric"><span>平均处置时长</span><strong>{metrics.averageResponseMinutes}</strong><small>分钟 · 已关闭告警</small></div></div>
    <div className="monitor-dashboard"><section className="panel"><div className="split"><h2>区域分布</h2><small>{domain === "typhoon" ? "真实杭州地图 · Open-Meteo 降水" : "示意底图 · 坐标为演示数据"}</small></div>{domain === "typhoon" ? <TyphoonRainMap /> : <AssetMap assets={scopedAssets} alerts={scopedAlerts} selectedId={selected?.id || ""} onSelect={setSelectedId} />}</section><section className="panel"><div className="split"><h2>{selected?.name || "监测趋势"}</h2>{selected && <StatusBadge mode={selected.source_mode}>{assetLabels[selected.asset_type] || selected.asset_type}</StatusBadge>}</div><TrendChart readings={selected ? scopedReadings.filter((item) => item.asset_id === selected.id) : []} />{selected && <p className="muted">{selected.area} · {selected.address} · 来源 {selected.source_code}</p>}</section></div>
    <section className="panel tablewrap"><div className="split"><h2>设备与测站台账</h2><small>最后心跳用于判断在线状态</small></div><table><thead><tr><th>设备</th><th>类型/区域</th><th>状态</th><th>最新值</th><th>数据来源</th></tr></thead><tbody>{scopedAssets.map((asset) => { const value = latest.get(asset.id); return <tr key={asset.id} onClick={() => setSelectedId(asset.id)} className={asset.id === selected?.id ? "selected-row" : ""}><td><b>{asset.name}</b><br /><small>{asset.code}</small></td><td>{assetLabels[asset.asset_type] || asset.asset_type}<br /><small>{asset.area}</small></td><td><StatusBadge mode={asset.status === "online" ? "real" : "external"}>{asset.status === "online" ? "在线" : asset.status === "offline" ? "离线" : "维护中"}</StatusBadge></td><td>{value ? <b>{value.value} {value.unit}</b> : "—"}<br /><small>{value ? new Date(value.measured_at).toLocaleString("zh-CN") : "暂无数据"}</small></td><td><StatusBadge mode={asset.source_mode}>{asset.source_mode === "simulated" ? "模拟适配器" : "外部接口"}</StatusBadge></td></tr>; })}</tbody></table></section>
    <div className="grid"><form className="panel form" action={(form) => onAddAsset(domain, form)}><h2>登记设备或测站</h2><label>编码<input name="code" required placeholder={domain === "typhoon" ? "TF-R-002" : "CS-G-002"} /></label><label>名称<input name="name" required /></label><label>类型<select name="assetType">{typeOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>区域<input name="area" required defaultValue="西湖区" /></label><label>地址<input name="address" /></label><div className="weight-grid"><label>经度<input name="longitude" type="number" step="0.000001" defaultValue="120.12" /></label><label>纬度<input name="latitude" type="number" step="0.000001" defaultValue="30.25" /></label><label>来源编码<input name="sourceCode" defaultValue={domain === "typhoon" ? "FLOOD_SIM" : "CITY_SIM"} /></label></div><button className="primary" disabled={!writable}>保存台账</button></form><form className="panel form" action={(form) => selected && onIngest(selected, form)}><h2>模拟适配器采集</h2><label>设备<select value={selected?.id || ""} onChange={(event) => setSelectedId(event.target.value)}>{scopedAssets.map((asset) => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></label><label>指标编码<input name="metricCode" required defaultValue={latest.get(selected?.id || "")?.metric_code || (domain === "typhoon" ? "rainfall_hour" : "gas_ppm")} /></label><div className="weight-grid"><label>监测值<input name="value" type="number" step="0.01" required /></label><label>单位<input name="unit" required defaultValue={latest.get(selected?.id || "")?.unit || "mm/h"} /></label><label>采集时间<input name="measuredAt" type="datetime-local" /></label></div><button className="primary" disabled={!writable || !selected}>写入监测值并执行规则</button><p className="muted">写入时自动匹配启用规则；同一设备、指标和规则的未关闭告警会合并计数。</p></form></div>
    <div className="grid"><form className="panel form" action={(form) => onAddRule(domain, form)}><h2>新增阈值规则</h2><label>规则名称<input name="name" required /></label><label>设备类型<select name="assetType">{typeOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>指标编码<input name="metricCode" required /></label><label>判断方向<select name="operator"><option value="gte">达到或超过</option><option value="lte">达到或低于</option></select></label><div className="weight-grid"><label>预警阈值<input name="warning" type="number" step="0.01" required /></label><label>严重阈值<input name="critical" type="number" step="0.01" required /></label><label>静默窗口（分钟）<input name="silence" type="number" min="1" defaultValue="30" /></label></div><button className="primary" disabled={!writable}>保存规则</button></form><section className="panel"><h2>当前规则</h2><div className="rule-list">{scopedRules.map((rule) => <article key={rule.id}><div><b>{rule.name}</b><p>{assetLabels[rule.asset_type] || rule.asset_type} · {rule.metric_code}</p></div><StatusBadge>{rule.operator === "gte" ? "≥" : "≤"} {rule.warning_threshold} / {rule.critical_threshold}</StatusBadge></article>)}</div></section></div>
    <section className="panel tablewrap"><div className="split"><h2>告警处置闭环</h2><small>认领 → 复核 → 转事件/关闭</small></div><table><thead><tr><th>告警对象</th><th>触发依据</th><th>去重</th><th>状态</th><th>操作</th></tr></thead><tbody>{scopedAlerts.map((alert) => { const asset = scopedAssets.find((item) => item.id === alert.asset_id); const rule = scopedRules.find((item) => item.id === alert.rule_id); return <tr key={alert.id}><td><b>{asset?.name}</b><br /><small>{asset?.area} · {alert.level === "critical" ? "严重" : "预警"}</small></td><td>{alert.metric_code}: <b>{alert.measured_value}</b><br /><small>{rule?.name || "阈值规则"} · 阈值 {alert.threshold_value}</small></td><td>累计 {alert.occurrence_count} 次<br /><small>{new Date(alert.last_triggered_at).toLocaleString("zh-CN")}</small></td><td><StatusBadge mode={alert.status === "closed" ? "real" : alert.level === "critical" ? "external" : "simulated"}>{alertLabels[alert.status]}</StatusBadge></td><td><div className="actions"><button disabled={!writable || alert.status !== "open"} onClick={() => onAlertAction(alert, "claim")}>认领</button><button disabled={!writable || !["claimed", "open"].includes(alert.status)} onClick={() => onAlertAction(alert, "verify")}>复核</button><button disabled={!writable || alert.status !== "verified"} onClick={() => onAlertAction(alert, "convert")}>转事件</button><button disabled={!writable || ["closed", "converted"].includes(alert.status)} onClick={() => onAlertAction(alert, "close")}>关闭</button></div></td></tr>; })}</tbody></table>{!scopedAlerts.length && <p className="empty">暂无告警。</p>}</section>
    <div className="grid"><section className="panel"><h2>近期处置轨迹</h2><div className="timeline">{actions.filter((action) => scopedAlerts.some((alert) => alert.id === action.alert_id)).slice(0, 8).map((action) => <article key={action.id}><b>{action.action}</b><p>{action.note}</p><small>{new Date(action.created_at).toLocaleString("zh-CN")}</small></article>)}</div></section><section className="panel dependency"><h2>数据适配器边界</h2><StatusBadge mode="simulated">演示适配器已贯通</StatusBadge><ul><li>标准输入：设备编码、指标、数值、单位、采集时间</li><li>标准输出：监测值、阈值命中、去重告警和处置轨迹</li><li>正式替换项：雨水风情、视频、物联网和城市安全接口凭据</li><li>正式验收项：接口时效、断线重连、数据准确性和网络白名单</li></ul><p>页面及业务规则不依赖具体供应商；取得接口文档后只需替换适配器，不需要重做业务页面。</p></section></div>
  </>;
}
