"use client";

import { useMemo, useState } from "react";
import { moduleMeta, productPages, tenderCoverage } from "@/lib/product-catalog";
import type { ActivityLog, EventRecord, OperationalRecord, ProductModule, Profile, RiskRecord, Role, TaskRecord } from "@/lib/types";
import type { ProductSnapshot } from "./emergency-app";

type RecordOps = { records: OperationalRecord[]; writable: boolean; onAdd: (module: ProductModule, form: FormData) => void; onUpdate: (record: OperationalRecord, status: string) => void; onDelete: (record: OperationalRecord) => void };
export function StatusBadge({ mode, children }: { mode?: OperationalRecord["source_mode"]; children: React.ReactNode }) { return <span className={`badge ${mode === "simulated" ? "orange" : mode === "external" ? "gray" : ""}`}>{children}</span>; }
function Metric({ title, value, note }: { title: string; value: number | string; note?: string }) { return <div className="metric"><span>{title}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }

export function OverviewPage({ stats, data, role, onSeed, onExport, onImport, importRef, importData }: { stats: { events: number; executing: number; resources: number; alerts: number }; data: ProductSnapshot; role: Role; onSeed: () => void; onExport: () => void; onImport: () => void; importRef: React.RefObject<HTMLInputElement | null>; importData: (file?: File) => void }) {
  return <><div className="pagehead"><div><span className="eyebrow">PRODUCT CONTROL CENTER</span><h1>从监测预警到复盘归档的完整产品</h1><p>真实业务数据、模拟外部数据和待接入能力分类呈现。</p></div><div className="actions"><button onClick={onImport}>导入快照</button><button onClick={onExport}>导出全量数据</button><button className="primary" disabled={role === "viewer"} onClick={onSeed}>初始化产品数据</button><input ref={importRef} hidden type="file" accept="application/json" onChange={(event) => importData(event.target.files?.[0])} /></div></div><div className="metrics"><Metric title="事件总数" value={stats.events} /><Metric title="执行中指令" value={stats.executing} /><Metric title="应急资源" value={stats.resources} /><Metric title="待处置预警" value={stats.alerts} /></div><div className="grid"><section className="panel"><h2>五大招标范围覆盖</h2><div className="coverage-list">{tenderCoverage.map((row) => <article key={row[0]}><div><b>{row[0]}</b><p>{row[1]}</p><small>{row[3]}</small></div><StatusBadge>{row[2]}</StatusBadge></article>)}</div></section><section className="panel"><h2>数据真实性说明</h2><ul className="legend"><li><StatusBadge mode="real">业务数据</StatusBadge>保存于数据库，可持续维护。</li><li><StatusBadge mode="simulated">模拟数据</StatusBadge>用于演示外部监测与设备行为。</li><li><StatusBadge mode="external">等待接入</StatusBadge>需要甲方或第三方授权。</li></ul><div className="summary-strip"><b>{data.records.filter((record) => record.source_mode === "real").length}</b><span>业务记录</span><b>{data.records.filter((record) => record.source_mode === "simulated").length}</b><span>模拟记录</span><b>{data.records.filter((record) => record.source_mode === "external").length}</b><span>外部依赖</span></div></section></div><section className="panel release"><h2>更新日志 · 2026-09-20</h2><p>已完成专业预案中心、资源匹配、库存单据原子记账与撤销冲销，以及风险普查导入批次、字段差异、批量派单、回写重试和对账状态。</p></section></>;
}

export function PortalPage({ data, role }: { data: ProductSnapshot; role: Role }) {
  const modules = productPages.filter((page) => !["overview", "portal", "logs", "admin"].includes(page.key));
  return <><div className="pagehead"><div><span className="eyebrow">ONE ORGANIZATION, ONE PLATFORM</span><h1>统一门户</h1><p>统一入口、统一用户、统一授权和统一接入管理。</p></div><StatusBadge>{role} 权限视图</StatusBadge></div><div className="app-grid">{modules.map((item) => <section className="app-card" key={item.key}><span>{item.group}</span><h2>{item.label}</h2><p>{item.key === "plans" ? `已建 ${data.plans.length} 项专业预案` : "已纳入统一产品导航与权限边界"}</p><StatusBadge>已接入门户</StatusBadge></section>)}</div><section className="panel dependency"><h2>浙政钉单点登录</h2><StatusBadge mode="external">等待甲方授权</StatusBadge><p>当前使用 Supabase 账号体系支撑公网协作。获得浙政钉应用标识、密钥、回调白名单和测试账号后，可替换认证适配器。</p></section></>;
}

function RecordForm({ module, onAdd }: { module: ProductModule; onAdd: RecordOps["onAdd"] }) { const meta = moduleMeta[module]; return <form className="panel form compact-form" action={(form) => onAdd(module, form)}><h2>新增{meta.title}记录</h2><label>分类<select name="recordType">{meta.types.map((type) => <option key={type}>{type}</option>)}</select></label><label>名称<input name="title" required /></label><label>状态<input name="status" defaultValue="正常" required /></label><label>区域<input name="area" /></label><label>责任机构<input name="ownerOrg" /></label><label>数据模式<select name="sourceMode"><option value="real">业务数据</option><option value="simulated">模拟数据</option><option value="external">等待外部接入</option></select></label><label>摘要<textarea name="summary" rows={3} /></label><label>扩展信息<textarea name="details" rows={2} placeholder="联系方式、库存、班次或接口说明" /></label><button className="primary">保存记录</button></form>; }
function RecordsTable({ records, writable, onUpdate, onDelete }: Omit<RecordOps, "onAdd">) { return <section className="panel tablewrap"><table><thead><tr><th>名称</th><th>分类/区域</th><th>状态</th><th>数据边界</th><th>操作</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><b>{record.title}</b><p>{record.summary}</p></td><td>{record.record_type}<br /><small>{record.area || "未设定"} · {record.owner_org || "未分配"}</small></td><td><StatusBadge>{record.status}</StatusBadge></td><td><StatusBadge mode={record.source_mode}>{record.source_mode === "real" ? "业务数据" : record.source_mode === "simulated" ? "模拟演示" : "等待接入"}</StatusBadge></td><td><div className="actions"><button disabled={!writable} onClick={() => onUpdate(record, record.status === "正常" ? "已复核" : "正常")}>更新</button><button disabled={!writable} onClick={() => onDelete(record)}>删除</button></div></td></tr>)}</tbody></table>{!records.length && <p className="empty">暂无记录</p>}</section>; }

export function ResourcesPage({ module = "resources", ...ops }: RecordOps & { module?: ProductModule }) { const meta = moduleMeta[module]; const records = ops.records.filter((record) => record.module === module); return <><div className="pagehead"><div><span className="eyebrow">OPERATIONAL MODULE</span><h1>{meta.title}</h1><p>{meta.description}</p></div><StatusBadge>{records.length} 条记录</StatusBadge></div><div className="grid"><RecordForm module={module} onAdd={ops.onAdd} /><RecordsTable records={records} writable={ops.writable} onUpdate={ops.onUpdate} onDelete={ops.onDelete} /></div></>; }
export function DutyPage(ops: RecordOps) { return <ResourcesPage {...ops} module="duty" />; }

export function PlansPage({ records, events, writable, onAdd, onDelete, onStart }: { records: OperationalRecord[]; events: EventRecord[]; writable: boolean; onAdd: RecordOps["onAdd"]; onDelete: RecordOps["onDelete"]; onStart: (event: EventRecord, plan: OperationalRecord) => void }) {
  const plans = records.filter((record) => record.module === "plans"); const [eventId, setEventId] = useState(""); const event = events.find((item) => item.id === eventId) || events[0];
  const ranked = useMemo(() => plans.map((plan) => { const type = String(plan.details.eventType || ""); const levels = Array.isArray(plan.details.levels) ? plan.details.levels : []; const keywords = Array.isArray(plan.details.keywords) ? plan.details.keywords : []; const score = event ? (type === event.event_type ? 50 : 0) + (levels.includes(event.response_level) ? 30 : 0) + (keywords.some((word) => event.description.includes(word)) ? 20 : 0) : 0; return { plan, score }; }).sort((a, b) => b.score - a.score), [plans, event]);
  return <><div className="pagehead"><div><span className="eyebrow">DIGITAL PLAN CENTER</span><h1>预案中心</h1><p>预案库、可解释规则匹配、人工确认和指令自动生成。</p></div><StatusBadge>规则匹配已实现</StatusBadge></div><div className="grid"><RecordForm module="plans" onAdd={onAdd} /><section className="panel"><h2>事件智能匹配</h2><label className="field">选择待研判事件<select value={event?.id || ""} onChange={(change) => setEventId(change.target.value)}>{events.map((item) => <option value={item.id} key={item.id}>{item.event_type} · {item.area} · {item.response_level}</option>)}</select></label>{!event && <p className="empty">请先在指挥调度中新增事件。</p>}{event && ranked.map(({ plan, score }) => <article className="recommend" key={plan.id}><div><b>{plan.title}</b><p>匹配分 {score}：类型 50 + 等级 30 + 关键词 20</p></div><div className="actions"><StatusBadge>{score}分</StatusBadge><button className="primary" disabled={!writable || score === 0} onClick={() => onStart(event, plan)}>人工确认并启动</button></div></article>)}</section></div><section className="panel tablewrap"><h2>预案库</h2><table><thead><tr><th>预案</th><th>版本/范围</th><th>匹配条件</th><th>状态</th><th>操作</th></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id}><td><b>{plan.title}</b><p>{plan.summary}</p></td><td>{String(plan.details.version || "V1.0")}<br />{plan.area}</td><td>{String(plan.details.eventType || "手工选择")}<br /><small>{Array.isArray(plan.details.keywords) ? plan.details.keywords.join("、") : "待配置"}</small></td><td>{plan.status}</td><td><button disabled={!writable} onClick={() => onDelete(plan)}>删除</button></td></tr>)}</tbody></table></section><section className="panel dependency"><h2>语义匹配与动态调整</h2><StatusBadge mode="external">模型评估基线待确认</StatusBadge><p>当前使用可解释的类型、等级和关键词规则。待提供真实预案语料、历史事件和验收准确率后可接入 NLP，保留人工复核。</p></section></>;
}

export function CommandPage({ events, tasks, writable, onAddEvent, onProgressEvent, onDeleteEvent, onAddTask, onProgressTask, onDeleteTask }: { events: EventRecord[]; tasks: TaskRecord[]; writable: boolean; onAddEvent: (form: FormData) => void; onProgressEvent: (event: EventRecord) => void; onDeleteEvent: (id: string) => void; onAddTask: (form: FormData) => void; onProgressTask: (task: TaskRecord) => void; onDeleteTask: (id: string) => void }) { return <><div className="pagehead"><div><span className="eyebrow">COMMAND & DISPATCH</span><h1>指挥调度</h1><p>事件建档、指令下达、已读反馈、完成跟踪和过程留痕。</p></div></div><div className="grid"><form className="panel form" action={onAddEvent}><h2>新增事件</h2><label>类型<select name="type"><option>暴雨内涝</option><option>台风</option><option>城市安全事件</option></select></label><label>响应等级<select name="level"><option>IV级</option><option>III级</option><option>II级</option><option>I级</option></select></label><label>区域<input name="area" required defaultValue="转塘街道" /></label><label>现场描述<textarea name="description" required rows={4} /></label><button className="primary" disabled={!writable}>保存事件</button></form><form className="panel form" action={onAddTask}><h2>手工下达指令</h2><label>任务<input name="title" required /></label><label>接收对象<input name="assignee" required /></label><label>调配资源<input name="resource" /></label><label>通知渠道<select name="channel"><option>平台内</option><option>短信（模拟）</option><option>移动端（模拟）</option><option>语音回呼（模拟）</option></select></label><label>时限（分钟）<input name="due" type="number" min="1" defaultValue="30" /></label><button className="primary" disabled={!writable}>下达指令</button></form></div><section className="panel tablewrap"><h2>事件台账</h2><table><thead><tr><th>事件</th><th>区域/等级</th><th>状态</th><th>操作</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><b>{event.event_type}</b><p>{event.description}</p></td><td>{event.area} · {event.response_level}</td><td><StatusBadge>{event.status}</StatusBadge></td><td><div className="actions"><button disabled={!writable || event.status === "已结案"} onClick={() => onProgressEvent(event)}>推进</button><button disabled={!writable} onClick={() => onDeleteEvent(event.id)}>删除</button></div></td></tr>)}</tbody></table></section><section className="panel tablewrap"><h2>指令跟踪</h2><table><thead><tr><th>指令</th><th>接收对象</th><th>渠道</th><th>状态</th><th>操作</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><b>{task.title}</b><p>{task.resource}</p></td><td>{task.assignee}</td><td>{task.channel || "平台内"}</td><td><StatusBadge>{task.status}</StatusBadge>{task.feedback && <p>{task.feedback}</p>}</td><td><div className="actions"><button disabled={!writable || task.status === "已完成"} onClick={() => onProgressTask(task)}>推进</button><button disabled={!writable} onClick={() => onDeleteTask(task.id)}>删除</button></div></td></tr>)}</tbody></table>{!tasks.length && <p className="empty">暂无指令。可在预案中心启动预案自动生成。</p>}</section></>; }

export function InventoryPage(ops: RecordOps) { const records = ops.records.filter((record) => record.module === "inventory"); const materials = records.filter((record) => record.record_type === "应急物资"); return <><div className="pagehead"><div><span className="eyebrow">INVENTORY CONTROL</span><h1>物资库存</h1><p>仓库、物资、入出库、调拨和库存预警留痕。</p></div></div><div className="metrics"><Metric title="物资品类" value={materials.length} /><Metric title="低于下限" value={materials.filter((record) => Number(record.details.quantity || 0) <= Number(record.details.minimum || 0)).length} /><Metric title="仓库/库点" value={records.filter((record) => record.record_type === "仓库").length} /><Metric title="出入库流水" value={records.filter((record) => ["入库单", "出库单", "调拨单"].includes(record.record_type)).length} /></div><div className="grid"><RecordForm module="inventory" onAdd={ops.onAdd} /><RecordsTable records={records} writable={ops.writable} onUpdate={ops.onUpdate} onDelete={ops.onDelete} /></div></>; }

export function RisksPage({ risks, writable, onAdd, onProgress, onDelete, onExport }: { risks: RiskRecord[]; writable: boolean; onAdd: (form: FormData) => void; onProgress: (risk: RiskRecord, status: RiskRecord["status"]) => void; onDelete: (id: string) => void; onExport: () => void }) { return <><div className="pagehead"><div><span className="eyebrow">RISK SURVEY WORKFLOW</span><h1>风险普查</h1><p>多源差异、属地派单、确认退回、回写留痕和字段导出。</p></div><button onClick={onExport}>导出CSV</button></div><form className="panel form form-wide" action={onAdd}><label>对象名称<input name="name" required /></label><label>区域<input name="area" required /></label><label>对象类型<input name="recordType" required /></label><label>数据来源<input name="source" required /></label><label>差异<select name="changeType"><option>新增</option><option>变更</option><option>删减</option></select></label><label>承办机构<input name="assignedOrg" /></label><label>原值<input name="oldValue" /></label><label>新值<input name="newValue" required /></label><button className="primary" disabled={!writable}>创建差异工单</button></form><section className="panel tablewrap"><table><thead><tr><th>对象</th><th>差异</th><th>变更内容</th><th>派单</th><th>状态/回写</th><th>操作</th></tr></thead><tbody>{risks.map((risk) => <tr key={risk.id}><td><b>{risk.name}</b><p>{risk.area} · {risk.record_type}</p></td><td>{risk.change_type}<br /><small>{risk.source}</small></td><td><s>{risk.old_value}</s><br /><b className="new">{risk.new_value}</b></td><td>{risk.assigned_org || "待分配"}</td><td><StatusBadge>{risk.status}</StatusBadge><p>{risk.writeback_message}</p></td><td><div className="actions">{risk.status === "待派单" && <button disabled={!writable} onClick={() => onProgress(risk, "待确认")}>派单</button>}{risk.status === "待确认" && <><button disabled={!writable} onClick={() => onProgress(risk, "已回写")}>确认回写</button><button disabled={!writable} onClick={() => onProgress(risk, "退回核查")}>退回</button></>}{risk.status === "退回核查" && <button disabled={!writable} onClick={() => onProgress(risk, "待确认")}>重派</button>}<button disabled={!writable} onClick={() => onDelete(risk.id)}>删除</button></div></td></tr>)}</tbody></table></section><section className="panel dependency"><h2>IRS 与应急数据仓</h2><StatusBadge mode="external">模拟适配器运行中</StatusBadge><p>产品已实现差异、派单、审核和回写状态机。获得真实接口后需补充字段映射、幂等键、异常重试和对账报告。</p></section></>; }

function ExternalPage({ title, module, onCreateEvent, ...ops }: RecordOps & { title: string; module: "monitoring" | "city_safety"; onCreateEvent: (record: OperationalRecord) => void }) { const records = ops.records.filter((record) => record.module === module); return <><div className="pagehead"><div><span className="eyebrow">MONITORING & EARLY WARNING</span><h1>{title}</h1><p>{moduleMeta[module].description}</p></div><StatusBadge mode="simulated">外部实时数据为模拟</StatusBadge></div><div className="monitor-grid">{records.map((record) => <article className={`monitor-card ${["超警", "待处置"].includes(record.status) ? "warning" : ""}`} key={record.id}><div className="split"><span>{record.record_type}</span><StatusBadge mode={record.source_mode}>{record.status}</StatusBadge></div><h2>{record.title}</h2><p>{record.summary}</p>{record.details.value !== undefined && <strong>{String(record.details.value)} {String(record.details.unit || "")}</strong>}<small>{record.area} · {record.owner_org}</small><div className="actions"><button disabled={!ops.writable || !["超警", "待处置"].includes(record.status)} onClick={() => onCreateEvent(record)}>转入事件研判</button><button disabled={!ops.writable} onClick={() => ops.onUpdate(record, record.status === "待处置" ? "已复核" : "正常")}>复核</button></div></article>)}</div><div className="grid"><RecordForm module={module} onAdd={ops.onAdd} /><section className="panel dependency"><h2>正式接入要求</h2><StatusBadge mode="external">等待外部环境</StatusBadge><ul><li>测站、设备和视频编码清单</li><li>实时数据接口与调用频率</li><li>告警阈值、断线规则和历史数据</li><li>政务网白名单和安全认证方式</li></ul><p>上方演示可完成预警复核和事件转入，但不宣称数值为真实监测数据。</p></section></div></>; }
export function TyphoonPage(props: RecordOps & { onCreateEvent: (record: OperationalRecord) => void }) { return <ExternalPage {...props} title="台汛卫士" module="monitoring" />; }
export function CityPage(props: RecordOps & { onCreateEvent: (record: OperationalRecord) => void }) { return <ExternalPage {...props} title="城市安全综合监管" module="city_safety" />; }

export function DataPage({ onExport, ...ops }: RecordOps & { onExport: () => void }) { const records = ops.records.filter((record) => record.module === "integrations"); return <><div className="pagehead"><div><span className="eyebrow">DATA & INTEGRATIONS</span><h1>数据管理与统一接入</h1><p>一数一源一标准，记录接入责任、所需资料和验收方法。</p></div><button onClick={onExport}>导出全量数据</button></div><div className="grid"><RecordForm module="integrations" onAdd={ops.onAdd} /><RecordsTable records={records} writable={ops.writable} onUpdate={ops.onUpdate} onDelete={ops.onDelete} /></div><section className="panel"><h2>接入状态看板</h2><div className="pipeline">{records.map((record) => <div key={record.id}><b>{record.record_type}</b><span>{record.title}</span><StatusBadge mode={record.source_mode}>{record.status}</StatusBadge><small>{Array.isArray(record.details.required) ? `所需：${record.details.required.join("、")}` : record.summary}</small></div>)}</div></section></>; }
export function LogsPage({ logs }: { logs: ActivityLog[] }) { return <><div className="pagehead"><div><span className="eyebrow">AUDIT TRAIL</span><h1>操作日志</h1><p>记录关键业务动作，用于追溯和问题复盘。</p></div></div><section className="panel records">{logs.map((log) => <article key={log.id}><div><b>{log.action}</b><p>{log.entity_type} · {new Date(log.created_at).toLocaleString("zh-CN")}</p></div></article>)}{!logs.length && <p className="empty">暂无日志</p>}</section></>; }
export function AdminPage({ profiles, records, onRoleChange, onAdd, onUpdate, onDelete }: { profiles: Profile[]; records: OperationalRecord[]; onRoleChange: (id: string, role: Role) => void; onAdd: RecordOps["onAdd"]; onUpdate: RecordOps["onUpdate"]; onDelete: RecordOps["onDelete"] }) { const organizations = records.filter((record) => record.module === "organizations"); return <><div className="pagehead"><div><span className="eyebrow">ADMINISTRATION</span><h1>后台管理</h1><p>成员角色、组织机构、工作群组和数据归属管理。</p></div></div><section className="panel tablewrap"><h2>成员与角色</h2><table><thead><tr><th>账号</th><th>组织/岗位</th><th>角色</th><th>权限调整</th></tr></thead><tbody>{profiles.map((profile) => <tr key={profile.id}><td>{profile.email || profile.display_name || "未填写"}</td><td>{profile.organization || "未分配"}<br /><small>{profile.job_title || "未设定"}</small></td><td><StatusBadge>{profile.role}</StatusBadge></td><td><select value={profile.role} onChange={(event) => onRoleChange(profile.id, event.target.value as Role)}><option value="viewer">viewer · 只读</option><option value="member">member · 业务维护</option><option value="admin">admin · 系统管理</option></select></td></tr>)}</tbody></table></section><div className="grid"><RecordForm module="organizations" onAdd={onAdd} /><RecordsTable records={organizations} writable onUpdate={onUpdate} onDelete={onDelete} /></div></>; }
