"use client";

import { useMemo, useRef, useState } from "react";
import { inventoryAlerts, recommendResources, resourcesMaintenanceAlerts } from "@/lib/resource-engine";
import type { EventRecord, InventoryBalance, InventoryDocument, InventoryDocumentLine, InventoryItem, ResourceAsset, Warehouse } from "@/lib/types";
import { StatusBadge } from "./product-pages";

const assetTypeText: Record<ResourceAsset["asset_type"], string> = { team: "队伍", expert: "专家", vehicle: "车辆", equipment: "装备", facility: "场所" };
const assetStatusText: Record<ResourceAsset["status"], string> = { available: "可调度", dispatched: "任务中", maintenance: "维保中", offline: "停用" };
const documentTypeText: Record<InventoryDocument["document_type"], string> = { inbound: "入库", outbound: "出库", transfer: "调拨" };
const documentStatusText: Record<InventoryDocument["status"], string> = { draft: "草稿", pending: "待审核", approved: "已记账", cancelled: "已撤销" };

export function ResourceCenterPage({ resources, events, activeEventId, writable, onAdd, onStatus, onImport, onExport }: {
  resources: ResourceAsset[]; events: EventRecord[]; writable: boolean;
  activeEventId?: string;
  onAdd: (form: FormData) => void; onStatus: (resource: ResourceAsset, status: ResourceAsset["status"]) => void;
  onImport: (file?: File) => void; onExport: () => void;
}) {
  const [eventId, setEventId] = useState(activeEventId || events[0]?.id || "");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const importRef = useRef<HTMLInputElement>(null);
  const event = events.find((item) => item.id === eventId) || events[0];
  const recommendations = useMemo(() => event ? recommendResources(event, resources).slice(0, 5) : [], [event, resources]);
  const maintenance = resourcesMaintenanceAlerts(resources);
  const filtered = resources.filter((item) => (!status || item.status === status) && `${item.name}${item.code}${item.area}${item.capabilities.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <div className="pagehead"><div><span className="eyebrow">RESOURCE DISPATCH</span><h1>应急资源</h1><p>队伍、专家、车辆、装备和场所独立建模，支持区域与能力推荐。</p></div><div className="actions"><button onClick={() => importRef.current?.click()}>导入Excel</button><button onClick={onExport}>导出Excel</button><input ref={importRef} hidden type="file" accept=".xlsx,.xls" onChange={(e) => onImport(e.target.files?.[0])} /></div></div>
    <div className="metrics"><div className="metric"><span>资源总数</span><b>{resources.length}</b></div><div className="metric"><span>可调度</span><b>{resources.filter((item) => item.status === "available").length}</b></div><div className="metric"><span>任务中</span><b>{resources.filter((item) => item.status === "dispatched").length}</b></div><div className="metric"><span>维保到期</span><b>{maintenance.length}</b></div></div>
    <div className="grid"><form className="panel form" action={onAdd}><h2>新增资源</h2><label>编码<input name="code" required placeholder="XH-TEAM-002" /></label><label>名称<input name="name" required /></label><label>类型<select name="assetType"><option value="team">队伍</option><option value="expert">专家</option><option value="vehicle">车辆</option><option value="equipment">装备</option><option value="facility">场所</option></select></label><label>区域<input name="area" required defaultValue="全区" /></label><label>地址<input name="address" /></label><label>联系人<input name="contactName" /></label><label>电话<input name="contactPhone" /></label><label>保障能力<input name="capabilities" placeholder="排涝,转移,急救" /></label><label>人数/能力值<input name="capacity" type="number" min="0" defaultValue="1" /></label><label>维保到期<input name="maintenanceDueAt" type="date" /></label><button className="primary" disabled={!writable}>保存资源</button></form>
      <section className="panel"><h2>事件周边资源推荐</h2>{event ? <><label className="field">事件<select value={event.id} onChange={(e) => setEventId(e.target.value)}>{events.map((item) => <option key={item.id} value={item.id}>{item.event_type} · {item.area}</option>)}</select></label>{recommendations.map((item) => <article className="recommend" key={item.resource.id}><div><b>{item.resource.name}</b><p>{item.reasons.join("；")}</p><small>{item.resource.area} · {item.resource.capabilities.join("、")}</small></div><StatusBadge>{item.score}分</StatusBadge></article>)}</> : <p className="empty">请先建立事件。</p>}</section></div>
    <section className="panel tablewrap"><div className="table-toolbar"><div><h2>资源台账</h2><small>按名称、编码、区域和能力检索</small></div><div className="filters-inline"><input aria-label="搜索应急资源" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索资源或能力" /><select aria-label="筛选资源状态" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option><option value="available">可调度</option><option value="dispatched">任务中</option><option value="maintenance">维保中</option><option value="offline">停用</option></select></div></div><table><thead><tr><th>资源</th><th>区域/位置</th><th>能力</th><th>联系</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><b>{item.name}</b><p>{item.code} · {assetTypeText[item.asset_type]}</p></td><td>{item.area}<br /><small>{item.address}</small></td><td>{item.capabilities.join("、") || "通用保障"}<br /><small>能力值 {item.capacity}</small></td><td>{item.contact_name}<br /><small>{item.contact_phone}</small></td><td><StatusBadge>{assetStatusText[item.status]}</StatusBadge>{item.maintenance_due_at && <p>维保 {item.maintenance_due_at.slice(0, 10)}</p>}</td><td><select disabled={!writable} aria-label={`更新${item.name}状态`} value={item.status} onChange={(e) => onStatus(item, e.target.value as ResourceAsset["status"])}><option value="available">可调度</option><option value="dispatched">任务中</option><option value="maintenance">维保中</option><option value="offline">停用</option></select></td></tr>)}</tbody></table>{!filtered.length && <p className="empty">当前筛选条件下没有资源。</p>}</section>
  </>;
}

export function InventoryCenterPage({ warehouses, items, balances, documents, lines, writable, admin, onAddWarehouse, onAddItem, onCreateDocument, onSubmit, onPost, onImport, onExport }: {
  warehouses: Warehouse[]; items: InventoryItem[]; balances: InventoryBalance[]; documents: InventoryDocument[]; lines: InventoryDocumentLine[];
  writable: boolean; admin: boolean; onAddWarehouse: (form: FormData) => void; onAddItem: (form: FormData) => void; onCreateDocument: (form: FormData) => void;
  onSubmit: (document: InventoryDocument) => void; onPost: (document: InventoryDocument, action: "approve" | "cancel") => void; onImport: (file?: File) => void; onExport: () => void;
}) {
  const importRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState("");
  const [documentStatus, setDocumentStatus] = useState("");
  const alerts = inventoryAlerts(balances, items, warehouses);
  const warehouseName = (id?: string | null) => warehouses.find((item) => item.id === id)?.name || "-";
  const itemName = (id: string) => items.find((item) => item.id === id)?.name || "未知物资";
  const filteredBalances = balances.filter((balance) => `${warehouseName(balance.warehouse_id)}${itemName(balance.item_id)}`.toLowerCase().includes(query.toLowerCase()));
  const filteredDocuments = documents.filter((document) => (!documentStatus || document.status === documentStatus) && `${document.document_no}${document.note}${warehouseName(document.from_warehouse_id)}${warehouseName(document.to_warehouse_id)}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <div className="pagehead"><div><span className="eyebrow">INVENTORY CONTROL</span><h1>仓储物资</h1><p>业务单据驱动库存；入库、出库、调拨审核后原子记账，支持撤销反向冲销。</p></div><div className="actions"><button onClick={() => importRef.current?.click()}>导入Excel</button><button onClick={onExport}>导出Excel</button><input ref={importRef} hidden type="file" accept=".xlsx,.xls" onChange={(e) => onImport(e.target.files?.[0])} /></div></div>
    <div className="metrics"><div className="metric"><span>仓库</span><b>{warehouses.length}</b></div><div className="metric"><span>物资品类</span><b>{items.length}</b></div><div className="metric"><span>待审核单据</span><b>{documents.filter((item) => item.status === "pending").length}</b></div><div className="metric"><span>库存预警</span><b>{alerts.length}</b></div></div>
    <div className="grid"><form className="panel form" action={onAddWarehouse}><h2>新增仓库</h2><label>编码<input name="code" required /></label><label>名称<input name="name" required /></label><label>区域<input name="area" required /></label><label>地址<input name="address" /></label><label>联系人<input name="contactName" /></label><label>电话<input name="contactPhone" /></label><button className="primary" disabled={!writable}>保存仓库</button></form><form className="panel form" action={onAddItem}><h2>新增物资目录</h2><label>SKU<input name="sku" required /></label><label>物资名称<input name="name" required /></label><label>分类<input name="category" required /></label><label>单位<input name="unit" required defaultValue="件" /></label><label>库存下限<input name="minQuantity" type="number" min="0" defaultValue="0" /></label><label>库存上限<input name="maxQuantity" type="number" min="0" defaultValue="1000" /></label><label>维保周期（天）<input name="maintenanceDays" type="number" min="1" defaultValue="365" /></label><button className="primary" disabled={!writable}>保存物资</button></form></div>
    <form className="panel form form-wide" action={onCreateDocument}><h2>新建库存业务单</h2><label>单据类型<select name="documentType"><option value="inbound">入库</option><option value="outbound">出库</option><option value="transfer">调拨</option></select></label><label>调出仓<select name="fromWarehouseId"><option value="">不适用</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>调入仓<select name="toWarehouseId"><option value="">不适用</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>物资<select name="itemId" required>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.unit}</option>)}</select></label><label>数量<input name="quantity" type="number" min="0.01" step="0.01" required /></label><label>备注<input name="note" /></label><button className="primary" disabled={!writable || !warehouses.length || !items.length}>创建草稿</button></form>
    <section className="panel tablewrap"><div className="table-toolbar"><div><h2>库存余额与预警</h2><small>库存上下限和可用数量实时计算</small></div><input aria-label="搜索库存" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索仓库、物资或单号" /></div><table><thead><tr><th>仓库</th><th>物资</th><th>库存</th><th>预留</th><th>可用</th><th>预警</th></tr></thead><tbody>{filteredBalances.map((balance) => { const item = items.find((candidate) => candidate.id === balance.item_id); const alert = alerts.find((candidate) => candidate.balance.id === balance.id); return <tr key={balance.id}><td>{warehouseName(balance.warehouse_id)}</td><td>{item?.name}<br /><small>{item?.sku}</small></td><td>{balance.quantity} {item?.unit}</td><td>{balance.reserved_quantity} {item?.unit}</td><td><b>{balance.quantity - balance.reserved_quantity} {item?.unit}</b></td><td>{alert ? <StatusBadge mode="external">{alert.message}</StatusBadge> : <StatusBadge mode="real">正常</StatusBadge>}</td></tr>; })}</tbody></table>{!filteredBalances.length && <p className="empty">当前条件下无库存记录。</p>}</section>
    <section className="panel tablewrap"><div className="table-toolbar"><div><h2>业务单据</h2><small>审核后记账；撤销生成反向冲销</small></div><select aria-label="筛选库存单据状态" value={documentStatus} onChange={(event) => setDocumentStatus(event.target.value)}><option value="">全部状态</option><option value="draft">草稿</option><option value="pending">待审核</option><option value="approved">已记账</option><option value="cancelled">已撤销</option></select></div><table><thead><tr><th>单号</th><th>类型/仓库</th><th>明细</th><th>状态</th><th>操作</th></tr></thead><tbody>{filteredDocuments.map((document) => <tr key={document.id}><td><b>{document.document_no}</b><p>{document.note}</p></td><td>{documentTypeText[document.document_type]}<br /><small>{warehouseName(document.from_warehouse_id)} → {warehouseName(document.to_warehouse_id)}</small></td><td>{lines.filter((line) => line.document_id === document.id).map((line) => <div key={line.id}>{itemName(line.item_id)} × {line.quantity}</div>)}</td><td><StatusBadge>{documentStatusText[document.status]}</StatusBadge></td><td><div className="actions">{document.status === "draft" && <button disabled={!writable} onClick={() => onSubmit(document)}>提交审核</button>}{document.status === "pending" && <button className="primary" disabled={!admin} onClick={() => onPost(document, "approve")}>审核并记账</button>}{document.status === "approved" && <button className="danger" disabled={!admin} onClick={() => onPost(document, "cancel")}>撤销并冲销</button>}</div></td></tr>)}</tbody></table>{!filteredDocuments.length && <p className="empty">当前筛选条件下暂无业务单据。</p>}</section>
  </>;
}
