"use client";

import { useMemo, useRef, useState } from "react";
import type { Organization, Profile, RiskFieldChange, RiskImportBatch, RiskRecord, RiskWritebackJob } from "@/lib/types";
import { StatusBadge } from "./product-pages";

const exportFields = ["对象名称", "区域", "对象类型", "数据来源", "差异类型", "原值", "新值", "状态", "承办机构"];

export function RiskSurveyCenterPage({ risks, batches, changes, jobs, profiles, organizations, writable, admin, onAdd, onBulkAssign, onTransition, onDelete, onImport, onExport, onRetry }: {
  risks: RiskRecord[]; batches: RiskImportBatch[]; changes: RiskFieldChange[]; jobs: RiskWritebackJob[]; profiles: Profile[]; organizations: Organization[];
  writable: boolean; admin: boolean; onAdd: (form: FormData) => void; onBulkAssign: (ids: string[], organizationId: string, userId: string) => void;
  onTransition: (risk: RiskRecord, action: "dispatch" | "confirm" | "return", reason?: string) => void; onDelete: (id: string) => void;
  onImport: (file: File | undefined, sourceCode: string) => void; onExport: (format: "csv" | "xlsx", fields: string[], rows: RiskRecord[]) => void; onRetry: (job: RiskWritebackJob) => void;
}) {
  const [area, setArea] = useState(""); const [recordType, setRecordType] = useState(""); const [source, setSource] = useState(""); const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<string[]>([]); const [assignOrg, setAssignOrg] = useState(""); const [assignUser, setAssignUser] = useState(""); const [sourceCode, setSourceCode] = useState("IRS_SIM");
  const [fields, setFields] = useState(exportFields); const [returnReasons, setReturnReasons] = useState<Record<string, string>>({});
  const importRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => risks.filter((risk) => (!area || risk.area === area) && (!recordType || risk.record_type === recordType) && (!source || risk.source === source) && (!status || risk.status === status)), [risks, area, recordType, source, status]);
  const unique = (key: "area" | "record_type" | "source") => [...new Set(risks.map((risk) => risk[key]).filter(Boolean))];
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const jobFor = (riskId: string) => jobs.find((job) => job.risk_record_id === riskId);
  return <>
    <div className="pagehead"><div><span className="eyebrow">RISK SURVEY WORKFLOW</span><h1>风险普查</h1><p>导入批次、字段差异、批量派单、确认退回、回写重试与对账闭环。</p></div><div className="actions"><select value={sourceCode} onChange={(e) => setSourceCode(e.target.value)}><option value="IRS_SIM">IRS 模拟适配器</option><option value="WAREHOUSE_SIM">应急数据仓模拟适配器</option></select><button onClick={() => importRef.current?.click()}>导入批次</button><input ref={importRef} hidden type="file" accept=".xlsx,.xls" onChange={(e) => onImport(e.target.files?.[0], sourceCode)} /></div></div>
    <div className="metrics"><div className="metric"><span>导入批次</span><b>{batches.length}</b></div><div className="metric"><span>待确认</span><b>{risks.filter((risk) => risk.status === "待确认").length}</b></div><div className="metric"><span>待回写/失败</span><b>{risks.filter((risk) => ["待回写", "回写失败"].includes(risk.status)).length}</b></div><div className="metric"><span>已回写</span><b>{risks.filter((risk) => risk.status === "已回写").length}</b></div></div>
    <section className="panel"><h2>筛选与导出</h2><div className="filter-grid"><label>区域<select value={area} onChange={(e) => setArea(e.target.value)}><option value="">全部</option>{unique("area").map((value) => <option key={value}>{value}</option>)}</select></label><label>类型<select value={recordType} onChange={(e) => setRecordType(e.target.value)}><option value="">全部</option>{unique("record_type").map((value) => <option key={value}>{value}</option>)}</select></label><label>来源<select value={source} onChange={(e) => setSource(e.target.value)}><option value="">全部</option>{unique("source").map((value) => <option key={value}>{value}</option>)}</select></label><label>状态<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部</option>{["待派单", "待确认", "退回核查", "待回写", "回写失败", "已回写"].map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="field-picker">{exportFields.map((field) => <label className="checkbox" key={field}><input type="checkbox" checked={fields.includes(field)} onChange={() => setFields((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field])} />{field}</label>)}</div><div className="actions"><button onClick={() => onExport("csv", fields, filtered)}>导出CSV</button><button onClick={() => onExport("xlsx", fields, filtered)}>导出Excel</button></div></section>
    <form className="panel form form-wide" action={onAdd}><h2>手工建立差异工单</h2><label>对象名称<input name="name" required /></label><label>区域<input name="area" required /></label><label>对象类型<input name="recordType" required /></label><label>数据来源<input name="source" required /></label><label>差异<select name="changeType"><option>新增</option><option>变更</option><option>删减</option></select></label><label>原值<input name="oldValue" /></label><label>新值<input name="newValue" required /></label><button className="primary" disabled={!writable}>创建工单</button></form>
    <section className="panel"><h2>批量派单</h2><div className="actions"><select value={assignOrg} onChange={(e) => { setAssignOrg(e.target.value); if (e.target.value) setAssignUser(""); }}><option value="">选择承办组织</option>{organizations.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={assignUser} onChange={(e) => { setAssignUser(e.target.value); if (e.target.value) setAssignOrg(""); }}><option value="">或选择承办人</option>{profiles.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.display_name || item.email}</option>)}</select><button className="primary" disabled={!admin || !selected.length || (!assignOrg && !assignUser)} onClick={() => onBulkAssign(selected, assignOrg, assignUser)}>派发 {selected.length} 条</button></div><small>修改工单归属属于管理员权限；承办组织成员登录后可确认或退回。</small></section>
    <section className="panel tablewrap"><h2>差异工单</h2><table><thead><tr><th>选择</th><th>对象</th><th>字段级差异</th><th>承办</th><th>回写/对账</th><th>操作</th></tr></thead><tbody>{filtered.map((risk) => { const riskChanges = changes.filter((item) => item.risk_record_id === risk.id); const job = jobFor(risk.id); return <tr key={risk.id}><td><input aria-label={`选择${risk.name}`} type="checkbox" checked={selected.includes(risk.id)} onChange={() => toggle(risk.id)} /></td><td><b>{risk.name}</b><p>{risk.area} · {risk.record_type}</p><small>{risk.source} · {risk.change_type}</small></td><td>{riskChanges.length ? riskChanges.map((change) => <div className="diff-row" key={change.id}><b>{change.field_name}</b><s>{change.old_value || "空"}</s><span>→</span><strong>{change.new_value || "空"}</strong></div>) : <div className="diff-row"><b>主要内容</b><s>{risk.old_value || "空"}</s><span>→</span><strong>{risk.new_value}</strong></div>}</td><td>{risk.assigned_org || "待分配"}<br /><StatusBadge>{risk.status}</StatusBadge>{risk.rejection_reason && <p>退回：{risk.rejection_reason}</p>}</td><td>{job ? <><StatusBadge mode={job.status === "succeeded" ? "real" : job.status === "failed" ? "external" : "simulated"}>{job.adapter_code} · {job.status}</StatusBadge><p>尝试 {job.attempt_count} 次</p><small>{job.error_message || risk.writeback_message}</small></> : "未建立回写任务"}</td><td><div className="actions vertical-actions">{risk.status === "待派单" && <button disabled={!writable || !risk.assigned_org} onClick={() => onTransition(risk, "dispatch")}>发送待确认</button>}{risk.status === "待确认" && <><button className="primary" disabled={!writable} onClick={() => onTransition(risk, "confirm")}>确认并回写</button><input aria-label={`${risk.name}退回理由`} placeholder="退回理由" value={returnReasons[risk.id] || ""} onChange={(e) => setReturnReasons((current) => ({ ...current, [risk.id]: e.target.value }))} /><button disabled={!writable || !returnReasons[risk.id]?.trim()} onClick={() => onTransition(risk, "return", returnReasons[risk.id])}>退回</button></>}{job?.status === "failed" && <button disabled={!writable} onClick={() => onRetry(job)}>重试回写</button>}<button disabled={!writable} onClick={() => onDelete(risk.id)}>删除</button></div></td></tr>; })}</tbody></table>{!filtered.length && <p className="empty">当前筛选条件下无数据。</p>}</section>
    <section className="panel tablewrap"><h2>导入批次</h2><table><thead><tr><th>批次</th><th>来源/文件</th><th>统计</th><th>状态</th></tr></thead><tbody>{batches.map((batch) => <tr key={batch.id}><td>{batch.batch_no}<br /><small>{new Date(batch.created_at).toLocaleString("zh-CN")}</small></td><td>{batch.source_code}<br /><small>{batch.file_name}</small></td><td>共 {batch.total_count} · 新增 {batch.created_count} · 变更 {batch.changed_count} · 删减 {batch.deleted_count}</td><td><StatusBadge mode={batch.status === "completed" ? "real" : batch.status === "failed" ? "external" : "simulated"}>{batch.status}</StatusBadge><p>{batch.error_message}</p></td></tr>)}</tbody></table></section>
    <section className="panel dependency"><h2>IRS 与应急数据仓适配层</h2><StatusBadge mode="simulated">可替换模拟适配器</StatusBadge><p>当前通过幂等键、尝试次数、失败状态、下次重试时间和响应摘要证明端到端流程。获得真实接口后仅替换适配器请求和字段映射。</p></section>
  </>;
}
